#!/usr/bin/env python
import sys
import pyasn
import random
import hmac

asndb = "ipasn.db"
rnd = (random.randrange(2**64)).to_bytes(8, byteorder='big')

asndb = pyasn.pyasn(asndb)
file_in = open(sys.argv[1], 'r')
file_out = open("{}.clean".format(sys.argv[1]), 'w')

for line in file_in:
	(ip, other) = line.split(' ', maxsplit=1)
	(asn, _) = asndb.lookup(ip)
	ip_hmac = hmac.new(rnd, msg=ip.encode('utf-8')).hexdigest()[:16]
	file_out.write("{}|{} {}".format(asn, ip_hmac, other))

